sites:
- id: 1
  name: 'Anime News Network'
  api_url: "http://cdn.animenewsnetwork.com/encyclopedia/api.xml?anime"
  format: "%s=%d"
  header: 'ann'
  xml_element:
    animation_type: 
    cast:
     tag: 'cast'
     property: null
     value: null
     
    creator: null
    director: null
    ending: 
     tag: 'info'
     property: 'type'
     value: 'Ending Theme'

    genre:
     tag: 'info'
     property: 'type'
     value: 'Genres'

    image:
     tag: 'info'
     property: 'type'
     value: 'Picture'
     inplace: 'src'

    number_of_episodes: 
     tag: 'info'
     property: 'type'
     value: 'Number of episodes'

    opening: 
     tag: 'info'
     property: 'type'
     value: 'Opening Theme'

    origin: null
    photograph_director: null
    studio: null
    title: 
     tag: 'info'
     property: 'type'
     value: 'Main title'
    theme:
     tag: 'info'
     property: 'type'
     value: 'Themes'
    year:
     tag: 'info'
     property: 'type'
     value: 'Vintage'
- id: 2
  name: 'Anime News Network Reviews'
  base_url: 'http://www.animenewsnetwork.com'
  #change api_url, year and season every anime-season
  api_url: 'http://www.animenewsnetwork.com/preview-guide/2014/fall/.79245'
  year: '2014'
  season: 'fall'
  format: '%s%s'
  xml_element:
    table:
     tag: 'table'
     property: null
     value: null
    animes:
     tag: 'td'
     property: null
     value: null
    name:
     tag: 'b'
     property: null
     value: null
    review_url:
     tag: 'a'
     property: 'href'
     value: True
     inplace: 'href'
    rating:
     tag: 'p'
     content: 'Rating'
     length: 50
     property: null
     value: null

